// swift-tools-version: 5.9
// KindaliveKit — pure-Swift port of the Kindalive neurochemical core.
//
// This package deliberately depends on Foundation only, so it builds and
// tests on Linux as well as Apple platforms. The Python package under
// `kindalive/` remains the source of truth; numerical parity is locked by
// the golden fixtures in Tests/KindaliveKitTests/Fixtures (generated by
// `scripts/generate_swift_fixtures.py`).

import PackageDescription

let package = Package(
    name: "KindaliveKit",
    platforms: [
        .iOS(.v15),
        .macOS(.v12),
    ],
    products: [
        .library(name: "KindaliveKit", targets: ["KindaliveKit"]),
    ],
    targets: [
        .target(name: "KindaliveKit"),
        .testTarget(
            name: "KindaliveKitTests",
            dependencies: ["KindaliveKit"],
            resources: [.copy("Fixtures")]
        ),
    ]
)
