// FixtureParityTests — the parity gate between the Swift port and the
// Python reference implementation.
//
// Every test loads a golden fixture generated by the Python engine
// (scripts/generate_swift_fixtures.py) and asserts near-equality.
// Tolerances: 1e-9 for single-formula cases (identical IEEE-754 double
// operations, modulo pow() ulps), 1e-6 for long accumulated trajectories.

import Foundation
import XCTest
@testable import KindaliveKit

private let formulaTolerance = 1e-9
private let trajectoryTolerance = 1e-6

final class DecayParityTests: XCTestCase {
    struct Fixture: Decodable {
        struct Case: Decodable {
            let chemical: String
            let start_level: Double
            let dt: Double
            let expected_level: Double
        }
        let cases: [Case]
    }

    func testDecayMatchesPython() throws {
        let fixture: Fixture = try loadFixture("decay")
        for c in fixture.cases {
            let chem = try XCTUnwrap(Chemical.from(string: c.chemical))
            let state = ChemicalState()
            state.set(chem, c.start_level)
            state.applyDecay(chem, dt: c.dt)
            XCTAssertEqual(
                state.get(chem), c.expected_level, accuracy: formulaTolerance,
                "decay \(c.chemical) from \(c.start_level) over \(c.dt)s"
            )
        }
    }
}

final class InteractionsParityTests: XCTestCase {
    struct Fixture: Decodable {
        struct StateSpec: Decodable {
            let levels: [String: Double]
            let baselines: [String: Double]
        }
        struct Case: Decodable {
            let name: String
            let dt: Double
            let scale: Double
            let input: StateSpec
            let expected: StateSpec
        }
        let cases: [Case]
    }

    func testInteractionsMatchPython() throws {
        let fixture: Fixture = try loadFixture("interactions")
        for c in fixture.cases {
            let state = makeState(levels: c.input.levels, baselines: c.input.baselines)
            applyInteractions(state, dt: c.dt, scale: c.scale)
            assertChemicalsEqual(
                state.asDict(), c.expected.levels,
                accuracy: formulaTolerance, context: "\(c.name) levels"
            )
            assertChemicalsEqual(
                state.baselinesAsDict(), c.expected.baselines,
                accuracy: formulaTolerance, context: "\(c.name) baselines"
            )
        }
    }
}

final class EngineTrajectoryParityTests: XCTestCase {
    struct Fixture: Decodable {
        struct ImpulseSpec: Decodable {
            let chemical: String
            let delta: Double
            let duration_seconds: Double?
            let source_id: String?
        }
        struct Snapshot: Decodable {
            let t: Double
            let levels: [String: Double]
            let baselines: [String: Double]
        }
        struct Scenario: Decodable {
            let personality: String
            let script: String
            let impulses: [ImpulseSpec]
            let snapshots: [Snapshot]
        }
        let scenarios: [Scenario]
    }

    func testTrajectoriesMatchPython() throws {
        let fixture: Fixture = try loadFixture("engine_trajectories")
        for scenario in fixture.scenarios {
            let clock = ManualClock()
            let engine = NeurochemicalEngine(
                clock: clock, seed: try getSeed(scenario.personality)
            )
            let impulses = scenario.impulses.map {
                ChemicalImpulse(
                    chemical: Chemical.from(string: $0.chemical)!,
                    delta: $0.delta,
                    durationSeconds: $0.duration_seconds ?? 0.0,
                    sourceId: $0.source_id ?? ""
                )
            }
            engine.applyImpulses(impulses)

            var t = 0.0
            for snap in scenario.snapshots {
                let dt = snap.t - t
                if dt > 0 {
                    clock.advance(seconds: dt)
                    engine.advance(dt: dt)
                    t = snap.t
                }
                let context = "\(scenario.personality)/\(scenario.script) @t=\(snap.t)"
                assertChemicalsEqual(
                    engine.state.asDict(), snap.levels,
                    accuracy: trajectoryTolerance, context: "\(context) levels"
                )
                assertChemicalsEqual(
                    engine.state.baselinesAsDict(), snap.baselines,
                    accuracy: trajectoryTolerance, context: "\(context) baselines"
                )
            }
        }
    }
}

final class SaturationParityTests: XCTestCase {
    struct Fixture: Decodable {
        struct ImpulseSpec: Decodable {
            let chemical: String
            let delta: Double
            let duration_seconds: Double?
            let source_id: String?
        }
        struct Step: Decodable {
            let advance: Double
            let impulse: ImpulseSpec
            let level_after: Double
        }
        struct Scenario: Decodable {
            let name: String
            let steps: [Step]
        }
        let scenarios: [Scenario]
    }

    func testSaturationMatchesPython() throws {
        let fixture: Fixture = try loadFixture("saturation")
        for scenario in fixture.scenarios {
            let clock = ManualClock()
            let engine = NeurochemicalEngine(clock: clock)
            for (i, step) in scenario.steps.enumerated() {
                clock.advance(seconds: step.advance)
                let chem = Chemical.from(string: step.impulse.chemical)!
                engine.applyImpulse(ChemicalImpulse(
                    chemical: chem,
                    delta: step.impulse.delta,
                    durationSeconds: step.impulse.duration_seconds ?? 0.0,
                    sourceId: step.impulse.source_id ?? ""
                ))
                XCTAssertEqual(
                    engine.state.get(chem), step.level_after,
                    accuracy: formulaTolerance,
                    "\(scenario.name) step \(i)"
                )
            }
        }
    }
}

final class EmotionParityTests: XCTestCase {
    struct Fixture: Decodable {
        struct StateSpec: Decodable {
            let levels: [String: Double]
            let baselines: [String: Double]
        }
        struct Case: Decodable {
            let input: StateSpec
            let expected: [String: Double]
        }
        let cases: [Case]
    }

    func testEmotionProjectionMatchesPython() throws {
        let fixture: Fixture = try loadFixture("emotions")
        for (i, c) in fixture.cases.enumerated() {
            let state = makeState(levels: c.input.levels, baselines: c.input.baselines)
            let emotions = EmotionProjection.compute(state)
            assertChemicalsEqual(
                emotions.asDict(), c.expected,
                accuracy: formulaTolerance, context: "emotions case \(i)"
            )
        }
    }
}

final class FaceParityTests: XCTestCase {
    struct Fixture: Decodable {
        struct StateSpec: Decodable {
            let levels: [String: Double]
            let baselines: [String: Double]
        }
        struct Case: Decodable {
            let input: StateSpec
            let expected: [String: Double]
        }
        let cases: [Case]
    }

    func testFaceProjectionMatchesPython() throws {
        let fixture: Fixture = try loadFixture("faces")
        for (i, c) in fixture.cases.enumerated() {
            let state = makeState(levels: c.input.levels, baselines: c.input.baselines)
            let face = FaceProjection.compute(state)
            assertChemicalsEqual(
                face.asDict(), c.expected,
                accuracy: formulaTolerance, context: "face case \(i)"
            )
        }
    }
}

final class FaceGeometryParityTests: XCTestCase {
    struct Fixture: Decodable {
        struct Case: Decodable {
            let name: String
            let muscles: [String: Double]
            let blink: Double
            let expected: Expected
        }
        struct Expected: Decodable {
            let smile: Double
            let open_k: Double
            let show_brow: Bool
            let happy_eyes: Bool
            let eye_center_x_right: Double
            let eye_center_y: Double
            let eye_rotation: Double
            let eye_half_height: Double
            let brow_inner_y: Double
            let brow_outer_y: Double
            let mouth_y: Double
            let mouth_half_width: Double
            let mouth_open: Bool
            let mouth_ellipse_center_y: Double
            let mouth_ellipse_ry: Double
            let mouth_curve_end_y: Double
            let mouth_curve_control_y: Double
        }
        let cases: [Case]
    }

    func testFaceGeometryMatchesReference() throws {
        let fixture: Fixture = try loadFixture("face_geometry")
        for c in fixture.cases {
            let g = FaceGeometry(muscles: c.muscles, blink: c.blink)
            let e = c.expected
            XCTAssertEqual(g.smile, e.smile, accuracy: formulaTolerance, c.name)
            XCTAssertEqual(g.openK, e.open_k, accuracy: formulaTolerance, c.name)
            XCTAssertEqual(g.showBrow, e.show_brow, c.name)
            XCTAssertEqual(g.happyEyes, e.happy_eyes, c.name)
            XCTAssertEqual(g.eyeCenterXRight, e.eye_center_x_right, accuracy: formulaTolerance, c.name)
            XCTAssertEqual(g.eyeCenterY, e.eye_center_y, accuracy: formulaTolerance, c.name)
            XCTAssertEqual(g.eyeRotation, e.eye_rotation, accuracy: formulaTolerance, c.name)
            XCTAssertEqual(g.eyeHalfHeight, e.eye_half_height, accuracy: formulaTolerance, c.name)
            XCTAssertEqual(g.browInnerY, e.brow_inner_y, accuracy: formulaTolerance, c.name)
            XCTAssertEqual(g.browOuterY, e.brow_outer_y, accuracy: formulaTolerance, c.name)
            XCTAssertEqual(g.mouthY, e.mouth_y, accuracy: formulaTolerance, c.name)
            XCTAssertEqual(g.mouthHalfWidth, e.mouth_half_width, accuracy: formulaTolerance, c.name)
            XCTAssertEqual(g.mouthOpen, e.mouth_open, c.name)
            XCTAssertEqual(g.mouthEllipseCenterY, e.mouth_ellipse_center_y, accuracy: formulaTolerance, c.name)
            XCTAssertEqual(g.mouthEllipseRy, e.mouth_ellipse_ry, accuracy: formulaTolerance, c.name)
            XCTAssertEqual(g.mouthCurveEndY, e.mouth_curve_end_y, accuracy: formulaTolerance, c.name)
            XCTAssertEqual(g.mouthCurveControlY, e.mouth_curve_control_y, accuracy: formulaTolerance, c.name)
        }
    }
}

final class VoiceParamsParityTests: XCTestCase {
    struct Fixture: Decodable {
        struct Case: Decodable {
            let emotions: [String: Double]
            let rate: Double
            let pitch: Double
        }
        let cases: [Case]
    }

    func testVoiceParamsMatchPython() throws {
        let fixture: Fixture = try loadFixture("voice_params")
        for (i, c) in fixture.cases.enumerated() {
            let e = c.emotions
            let emotions = EmotionVector(
                happiness: e["happiness"]!, excitement: e["excitement"]!,
                anger: e["anger"]!, calm: e["calm"]!,
                bonding: e["bonding"]!, anxiety: e["anxiety"]!,
                sadness: e["sadness"]!, euphoria: e["euphoria"]!
            )
            let params = VoiceParams(emotions: emotions)
            XCTAssertEqual(params.rate, c.rate, accuracy: formulaTolerance, "rate case \(i)")
            XCTAssertEqual(params.pitch, c.pitch, accuracy: formulaTolerance, "pitch case \(i)")
        }
    }
}
