// Shared helpers for loading the golden parity fixtures generated by
// scripts/generate_swift_fixtures.py (run from the repo root).

import Foundation
import XCTest
@testable import KindaliveKit

func loadFixture<T: Decodable>(_ name: String, as type: T.Type = T.self) throws -> T {
    guard let url = Bundle.module.url(
        forResource: name, withExtension: "json", subdirectory: "Fixtures"
    ) else {
        throw NSError(
            domain: "FixtureSupport", code: 1,
            userInfo: [NSLocalizedDescriptionKey: "Missing fixture \(name).json — run scripts/generate_swift_fixtures.py"]
        )
    }
    return try JSONDecoder().decode(T.self, from: Data(contentsOf: url))
}

/// Build a ChemicalState from fixture levels/baselines keyed by name.
func makeState(levels: [String: Double], baselines: [String: Double]? = nil) -> ChemicalState {
    var baselineDict: [Chemical: Double]?
    if let baselines {
        baselineDict = Dictionary(
            uniqueKeysWithValues: baselines.compactMap { key, value in
                Chemical.from(string: key).map { ($0, value) }
            }
        )
    }
    let state = ChemicalState(baselines: baselineDict)
    for (name, value) in levels {
        if let chem = Chemical.from(string: name) {
            state.set(chem, value)
        }
    }
    return state
}

/// Assert two chemical dictionaries match within tolerance, reporting the
/// chemical name (and a caller-supplied context) on failure.
func assertChemicalsEqual(
    _ actual: [String: Double],
    _ expected: [String: Double],
    accuracy: Double,
    context: String,
    file: StaticString = #filePath,
    line: UInt = #line
) {
    for (name, expectedValue) in expected.sorted(by: { $0.key < $1.key }) {
        guard let actualValue = actual[name] else {
            XCTFail("\(context): missing \(name)", file: file, line: line)
            continue
        }
        XCTAssertEqual(
            actualValue, expectedValue, accuracy: accuracy,
            "\(context): \(name)", file: file, line: line
        )
    }
}
